# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings, .isort.cfg]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        additional_dependencies:
          - lxml
          - pydantic
          - types-pyyaml
          - types-requests
          - types-setuptools
          - types-toml

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-eradicate
          - flake8-logging-format

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        entry: pydocstyle

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        entry: bandit
        args:
          - -c
          - pyproject.toml
          - -f
          - html
          - -o
          - .reports/bandit.html

        additional_dependencies: [toml]

  - repo: local
    hooks:
      {%- if cookiecutter.with_commitizen %}
      - id: commitizen
        name: commitizen
        entry: cz check --commit-msg-file
        require_serial: true
        language: system
        stages: [commit-msg]
      {%- endif %}
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py{{ cookiecutter.python_version|replace(".", "") }}-plus
        require_serial: true
        language: system
        types: [python]
      - id: absolufy-imports
        name: absolufy-imports
        entry: absolufy-imports
        require_serial: true
        language: system
        types: [python]
      - id: yesqa
        name: yesqa
        entry: yesqa
        require_serial: true
        language: system
        types: [python]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck --check-sourced
        language: system
        types: [shell]
      - id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: false
